#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ShikkhanobishTeacherApp.Droid.Resource", IsApplication=true)]

namespace ShikkhanobishTeacherApp.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010002
			public const int colorAccent = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimary = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int colorPrimaryDark = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int launcher_background = 2130771973;
			
			// aapt resource value: 0x7F010000
			public const int ListViewHighlighted = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int ListViewSelected = 2130771969;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int appiconteacher = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int backbtn = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int blacklogo = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int congts = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int favourite = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int feedbackback = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int icon_about = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int icon_feed = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int monetization = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int nointernetconnection = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int off = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int on = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int onlylogo = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int profilebac = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int rating = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int report = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int selectionstatus = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int shikcon = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int splash = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int splashscreenlogo = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int subject = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int teacher = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int teacherregback = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int totalmin = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int tuition = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int withdraw = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int xamarin_logo = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon_round = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int shikcon = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int SplashTheme = 2130968577;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
